package menu;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public class Register extends javax.swing.JFrame {
    int xx, xy;

    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connection mysqlconfig;
    }

    private static Connection mysqlconfig;
    Connection con;
    PreparedStatement pst;
    public static Connection configDB() throws SQLException {
        try {
            String url = "jdbc:mysql://localhost:3306/bakery?useSSL=false&serverTimezone=UTC";
            String user = "root"; // Sesuaikan dengan username Anda
            String password = ""; // Isi dengan password MySQL Anda

            DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
            mysqlconfig = DriverManager.getConnection(url, user, password);
            System.out.println("Koneksi Berhasil");
        } catch (SQLException e) {
            System.err.println("Koneksi gagal: " + e.getMessage());
            throw new SQLException("Tidak dapat terhubung ke database");
        }
        return mysqlconfig;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text_usernameregister = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_passwordregister = new javax.swing.JPasswordField();
        jButton_create = new javax.swing.JButton();
        jButto_cancel = new javax.swing.JButton();
        lihatpassword = new javax.swing.JCheckBox();
        text_nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        color2 = new menu.color();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_usernameregister.setBackground(new java.awt.Color(235, 235, 235));
        text_usernameregister.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        text_usernameregister.setBorder(null);
        text_usernameregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameregisterActionPerformed(evt);
            }
        });
        jPanel1.add(text_usernameregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 224, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Username :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 155, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Password  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 195, -1, -1));

        text_passwordregister.setBackground(new java.awt.Color(235, 235, 235));
        text_passwordregister.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        text_passwordregister.setBorder(null);
        text_passwordregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passwordregisterActionPerformed(evt);
            }
        });
        jPanel1.add(text_passwordregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 224, 30));

        jButton_create.setBackground(new java.awt.Color(102, 0, 102));
        jButton_create.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_create.setForeground(new java.awt.Color(255, 255, 255));
        jButton_create.setText("Create");
        jButton_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 85, 35));

        jButto_cancel.setBackground(new java.awt.Color(102, 0, 102));
        jButto_cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButto_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButto_cancel.setText("Cancel");
        jButto_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButto_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 85, 35));

        lihatpassword.setBorder(null);
        lihatpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(lihatpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        text_nama.setBackground(new java.awt.Color(235, 235, 235));
        text_nama.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        text_nama.setBorder(null);
        text_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaActionPerformed(evt);
            }
        });
        jPanel1.add(text_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 224, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Nama        :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 115, 90, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("I have  an account, Login");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 320, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 380, 330));

        color2.setColorEnd(new java.awt.Color(204, 204, 204));
        color2.setColorStart(new java.awt.Color(102, 0, 102));
        color2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Haway-removebg-preview.png"))); // NOI18N
        color2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 330));

        getContentPane().add(color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_usernameregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameregisterActionPerformed

    private void text_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaActionPerformed

    private void text_passwordregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passwordregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passwordregisterActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Loginn log = new Loginn();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createActionPerformed
        try {
            configDB();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    try {
        // Menginisialisasi koneksi
        con = configDB();

        // Mengambil nilai dari form input
        String nama = text_nama.getText().trim();
        String username = text_usernameregister.getText().trim();
        String password = String.valueOf(text_passwordregister.getPassword()).trim();

        // Validasi input kosong
        if (nama.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap mengisi semua field!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Query insert ke database
        pst = con.prepareStatement("INSERT INTO user (Id_user, Nama, Username, Password) VALUES (?, ?, ?, ?)");
        pst.setString(1, null);
        pst.setString(2, nama);
        pst.setString(3, username);
        pst.setString(4, password);
        // Eksekusi query
        int result = pst.executeUpdate();

        // Menampilkan hasil operasi
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Registrasi berhasil!");
                Loginn log = new Loginn();
                log.setVisible(true);
                log.pack();
                log.setLocationRelativeTo(null);
                this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal, silakan coba lagi!");
        }

    } catch (SQLException ex) {
        Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: ");
    }
    }//GEN-LAST:event_jButton_createActionPerformed

    private void lihatpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatpasswordActionPerformed
      if(lihatpassword.isSelected()){
      text_passwordregister.setEchoChar((char)0);
       }
       else{
       text_passwordregister.setEchoChar('*');
       }
    }//GEN-LAST:event_lihatpasswordActionPerformed

    private void jButto_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButto_cancelActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private menu.color color2;
    private javax.swing.JButton jButto_cancel;
    private javax.swing.JButton jButton_create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox lihatpassword;
    private javax.swing.JTextField text_nama;
    private javax.swing.JPasswordField text_passwordregister;
    private javax.swing.JTextField text_usernameregister;
    // End of variables declaration//GEN-END:variables




}
